addSbtPlugin("com.dwijnand"      % "sbt-dynver"    % "4.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.4.3")
addSbtPlugin("io.spray"          % "sbt-revolver"  % "0.9.1")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"  % "0.14.10")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.9.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"  % "0.9.34")
